# Generated by Django 5.0.3 on 2025-05-11 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("EASYOCR", "EasyOCR"),
                            ("PYTESSERACT", "Pytesseract"),
                            ("KERASOCR", "KerasOCR"),
                        ],
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("word", models.CharField(max_length=255)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="app.image",
                    ),
                ),
            ],
        ),
    ]
