# Generated by Django 5.0.3 on 2025-05-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
